## Initial settings
title: Marcos Urios Portfolio
notificationColor: 172433

## Site settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://marcosurios.com" # the base hostname & protocol for your site
twitter_username: Marcosaurios
linkedin_username: marcosurios
github_username:  Marcosaurios
artstation_usermane: marcosaurios
sketchfab_username: marcosaurios


############
## Jekyll ##
############
# Extra collections
collections:
  projects:
    output: true

jekyll-minifier:
  compress_css: false                # Default: true
  compress_javascript: true         # Default: true

sass:
  sass_dir: assets/_sass
  style: compressed

# kramdown:  
#   html_to_native: true

# Responsive pics
## -- origin_url: /                           -> Local (relative to host url)
## -- origin_url: https://www.marcosurios.com -> PRODUCTION (relative to my website url)
# if not: Cloudinary won't be able to compress files
## -- only_prod: true -> Local
cloudinary:
  cloud_name: Marcosaurios
  # origin_url: /
  # only_prod: true
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "100vw"
      # sizes: "(min-width: 50rem) 50rem, 90vw"

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data

plugins:
  - jekyll-liquify
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-cloudinary

highlighter: rouge

