## Initial settings
title: Marcos Urios Portfolio
notificationColor: 172433

## Deploy: origin_url: sitename
## Local: origin_url: /

baseurl: "/" # the subpath of your site, e.g. /blog
url: https://www.marcosurios.com # the base hostname & protocol for your site
# url: /
twitter_username: Marcosaurios
linkedin_username: marcosurios
github_username:  Marcosaurios
artstation_usermane: marcosaurios
sketchfab_username: marcosaurios


############
## Jekyll ##
############
# Extra collections
collections:
  projects:
    output: true

# include: [ '_redirects']

# Responsive pics
## -- origin_url: /                           -> Local (relative to host url)
## -- origin_url: https://www.marcosurios.com -> PRODUCTION (relative to my website url)
cloudinary:
  cloud_name: Marcosaurios
  only_prod: false          # local = true
  origin_url: https://www.marcosurios.com
  # origin_url: / # local
  # origin_url: https://dazzling-wright-08e708.netlify.com
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 100vw"

highlighter: rouge

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data

jekyll-minifier:
  compress_javascript: true         
  # compress_css: false   # already compressed in SASS           

sass:
  sass_dir: assets/_sass
  style: compressed

plugins:
  - jekyll-liquify
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-cloudinary


