# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/imgs'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    editor:
      preview: true
    fields:
    - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Ref', name: 'ref', widget: 'string' }
    - { label: 'Language', name: 'lang', widget: 'string', default: 'es'}
    - { label: 'Author', name: 'author', widget: 'string' , default: 'Marcos'}
    - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', default: 'Marcos'}
    - { label: 'Body', name: 'body', widget: 'markdown' } # todo: CATEGORIES and MEDIA
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    create: true
    editor:
      preview: true
    fields:
    - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Ref', name: 'ref', widget: 'string' }
    - { label: 'Language', name: 'lang', widget: 'string', default: 'es'}
    - { label: 'Author', name: 'author', widget: 'string' , default: 'Marcos'}
    - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', default: 'Marcos'}
    - { label: 'Body', name: 'body', widget: 'markdown' } # todo: CATEGORIES and MEDIA
  - name: 'pages'
    label: 'Pages'
    folder: '/'
    create: true
    editor:
      preview: true
    fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
    - { label: 'Author', name: 'author', widget: 'string' , default: 'Marcos'}
    - { label: 'Ref', name: 'ref', widget: 'string' }
    - { label: 'Language', name: 'lang', widget: 'string', default: 'es'}
    - { label: 'Permalink', name: 'permalink', widget: 'string'}
    - { label: 'Body', name: 'body', widget: 'markdown' } # todo: CATEGORIES and MEDIA